baseURL = "https://orioninsistcyber.com/"
languageCode = "en-us"
title = "OrionInsist Cyber"
theme = "PaperMod"

[params]
author = "Murat"
description = "Cybersecurity, Linux, and Tech Blog"
ShowReadingTime = true
ShowShareButtons = true
ShowToc = true
TocOpen = true

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 4

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 5

