baseURL = "https://orioninsistcyber.com/"
languageCode = "en-us"
title = "OrionInsist Cyber"

[params]
env = "production"
author = "Murat"
description = "Cybersecurity, Linux, and Tech Blog"
ShowReadingTime = true
ShowShareButtons = true
ShowToc = true
TocOpen = true
googleAnalytics = "G-J530VWHL4Q"
googleAnalyticsPartial = "partials/google_analytics.html"


[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 4



